{% set name = "kedro-light" %}
{% set version = "2023.3.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/kedro-light-{{ version }}.tar.gz
  sha256: eac29b2a0ab3fb5c311c6701cfb9d0c2649975c9e4e92944a26b0f14e4bd5003

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - kedro
    - kedro-viz

test:
  imports:
    - kedro_light
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: A lightweight interface to Kedro and Kedro-Viz
  home: https://github.com/ellwise/kedro-light
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
